# Generated by Django 5.2.8 on 2025-11-27 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('sekolah', models.CharField(max_length=200)),
                ('kecamatan', models.CharField(blank=True, max_length=100, null=True)),
                ('jenjang', models.CharField(choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA')], max_length=10)),
                ('sesi', models.CharField(choices=[('IN1', 'IN-1'), ('ON', 'ON'), ('IN2', 'IN-2')], max_length=10)),
                ('skor_kepuasan', models.FloatField(default=0)),
                ('saran_masukan', models.TextField(blank=True, null=True)),
                ('rencana_implementasi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.IntegerField()),
                ('instrumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.instrumen')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_set', to='reporting.peserta')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.trainer')),
            ],
            options={
                'unique_together': {('peserta', 'trainer', 'instrumen')},
            },
        ),
    ]
