# Generated by Django 5.2.8 on 2025-12-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('sekolah', models.CharField(max_length=200)),
                ('kecamatan', models.CharField(blank=True, max_length=100, null=True)),
                ('skor_kepuasan', models.FloatField(default=0)),
                ('saran_masukan', models.TextField(blank=True, null=True)),
                ('rencana_implementasi', models.TextField(blank=True, null=True)),
                ('data_trainer', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
