# Generated by Django 5.2.8 on 2025-11-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peserta',
            name='materi_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
